version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ~/mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 1111
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   test_db:
     depends_on:
       - db
     image: wangxian/alpine-mysql:latest
     volumes:
       - ~/test.sh:/tmp

   wordpress:
     depends_on:
       - db
       - test_db
     image: wordpress:latest
     ports:
       - "81:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     deploy:
       replicas: 1
       update_config:
         parallelism: 1
         delay: 10s
         failure_action: rollback
volumes:
    db_data: {}
